# Generated by Django 3.0.6 on 2020-05-28 23:26

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=smartfields.fields.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
